# Generated by Django 4.0.3 on 2022-03-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture5_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture5_app',
            name='author',
            field=models.CharField(default='anon', max_length=30),
        ),
        migrations.AddField(
            model_name='lecture5_app',
            name='describe',
            field=models.TextField(default='DataFlair Django tutorials'),
        ),
        migrations.AddField(
            model_name='lecture5_app',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='lecture5_app',
            name='picture',
            field=models.ImageField(default='default value', upload_to=''),
        ),
    ]
