# Generated by Django 4.0.3 on 2022-03-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture5_app', '0002_lecture5_app_author_lecture5_app_describe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('picture', models.ImageField(default='default value', upload_to='')),
                ('author', models.CharField(default='anon', max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('describe', models.TextField(default='DataFlair Django tutorials')),
            ],
            options={
                'verbose_name': 'Спорт',
                'verbose_name_plural': 'Спортсмены',
                'ordering': ['-author', 'title'],
            },
        ),
        migrations.AlterModelOptions(
            name='lecture5_app',
            options={'ordering': ['-author', 'title'], 'verbose_name': 'Рассказ', 'verbose_name_plural': 'Рассказы'},
        ),
    ]
